# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ML_APP.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os
import cv2
import numpy as np


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 80, 541, 51))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(85, 0, 0);")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 741, 561))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(230, 60, 341, 121))
        self.pushButton.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 270, 261, 211))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(450, 180, 251, 261))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(70, 210, 251, 211))
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 480, 75, 41))
        self.pushButton_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(9, -1, 691, 551))
        self.frame_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(60, 70, 151, 51))
        self.label_5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(364, 80, 191, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(-10, 0, 691, 551))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 661, 221))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 270, 161, 31))
        self.pushButton_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_2.setGeometry(QtCore.QRect(15, 341, 671, 201))
        self.textBrowser_2.setObjectName("textBrowser_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuImage_processing = QtWidgets.QMenu(self.menubar)
        self.menuImage_processing.setObjectName("menuImage_processing")
        self.menuText_processing = QtWidgets.QMenu(self.menubar)
        self.menuText_processing.setObjectName("menuText_processing")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDace_detect = QtWidgets.QAction(MainWindow)
        self.actionDace_detect.setObjectName("actionDace_detect")
        self.actionFace_recognition = QtWidgets.QAction(MainWindow)
        self.actionFace_recognition.setObjectName("actionFace_recognition")
        self.actionDigits_recognition = QtWidgets.QAction(MainWindow)
        self.actionDigits_recognition.setObjectName("actionDigits_recognition")
        self.actionOther_object_detection = QtWidgets.QAction(MainWindow)
        self.actionOther_object_detection.setObjectName("actionOther_object_detection")
        self.actionText_summariser = QtWidgets.QAction(MainWindow)
        self.actionText_summariser.setObjectName("actionText_summariser")
        self.actionText_classification = QtWidgets.QAction(MainWindow)
        self.actionText_classification.setObjectName("actionText_classification")
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuImage_processing.addAction(self.actionDace_detect)
        self.menuImage_processing.addAction(self.actionFace_recognition)
        self.menuImage_processing.addAction(self.actionDigits_recognition)
        self.menuImage_processing.addAction(self.actionOther_object_detection)
        self.menuText_processing.addAction(self.actionText_summariser)
        self.menuText_processing.addAction(self.actionText_classification)
        self.menuOptions.addAction(self.actionHome)
        self.menuOptions.addAction(self.actionExit)
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuImage_processing.menuAction())
        self.menubar.addAction(self.menuText_processing.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "welcome to machine learning applications"))
        self.pushButton.setText(_translate("MainWindow", "choose image"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "detect faces"))
        self.label_5.setText(_translate("MainWindow", "face recognition"))
        self.pushButton_3.setText(_translate("MainWindow", "face recognition"))
        self.pushButton_4.setText(_translate("MainWindow", "digit recognition"))
        self.menuImage_processing.setTitle(_translate("MainWindow", "image processing"))
        self.menuText_processing.setTitle(_translate("MainWindow", "text processing"))
        self.menuOptions.setTitle(_translate("MainWindow", "options"))
        self.actionDace_detect.setText(_translate("MainWindow", "face detect"))
        self.actionFace_recognition.setText(_translate("MainWindow", "face recognition"))
        self.actionDigits_recognition.setText(_translate("MainWindow", "digits recognition"))
        self.actionOther_object_detection.setText(_translate("MainWindow", "other object detection"))
        self.actionText_summariser.setText(_translate("MainWindow", "text summariser"))
        self.actionText_classification.setText(_translate("MainWindow", "text classification"))
        self.actionHome.setText(_translate("MainWindow", "home"))
        self.actionExit.setText(_translate("MainWindow", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

